// embed-assets.js
// 画像と quest-answers.json を HTML にインライン埋め込みする
const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, 'english-app.html');
const imgDir   = path.join(__dirname, '英語アプリ画像');
const jsonPath = path.join(__dirname, 'quest-answers.json');

let html = fs.readFileSync(htmlPath, 'utf8');

// ── 1. 画像を base64 data URI に変換 ────────────────────────────
const imageNames = ['desktop-icon', 'emma_main', 'emma_happy', 'emma_surprise', 'emma_worry'];
const imgData = {};
imageNames.forEach(name => {
  const buf = fs.readFileSync(path.join(imgDir, name + '.png'));
  imgData[name] = 'data:image/png;base64,' + buf.toString('base64');
  console.log(`Embedded ${name}.png (${Math.round(buf.length/1024)}KB)`);
});

// ── 2. quest-answers.json を JS オブジェクトとして埋め込み ────────
const questAnswersRaw = fs.readFileSync(jsonPath, 'utf8');
console.log(`Embedded quest-answers.json (${Math.round(questAnswersRaw.length/1024)}KB)`);

// ── 3. EMMA_ASSETS 定数ブロックを <script> 直後に挿入 ────────────
const assetsBlock = `
// ════════════════════════════════════════════════════════════
// EMBEDDED ASSETS (auto-generated by embed-assets.js)
// ════════════════════════════════════════════════════════════
const EMMA_IMAGES = {
  'desktop-icon': '${imgData['desktop-icon']}',
  'emma_main':    '${imgData['emma_main']}',
  'emma_happy':   '${imgData['emma_happy']}',
  'emma_surprise':'${imgData['emma_surprise']}',
  'emma_worry':   '${imgData['emma_worry']}'
};
const QUEST_ANSWERS_INLINE = ${questAnswersRaw};
`;

// <script> タグの直後に挿入
html = html.replace(/(<script>)/, '$1' + assetsBlock);

// ── 4. ロゴの img src を data URI に置換 ─────────────────────────
html = html.replace(
  /src="英語アプリ画像\/desktop-icon\.png"/g,
  `src="${imgData['desktop-icon']}"`
);

// ── 5. emmaAvHTML() 関数を data URI 参照に差し替え ───────────────
html = html.replace(
  /function emmaAvHTML\(expr\) \{[\s\S]*?return `<img class="expr-img".*?`;\s*\}/,
  `function emmaAvHTML(expr) {
  const src = EMMA_IMAGES[expr] || EMMA_IMAGES['emma_main'];
  return \`<img class="expr-img" src="\${src}" alt="Emma" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="expr-fallback">E</div>\`;
}`
);

// ── 6. fetch('quest-answers.json') を INLINE データ参照に差し替え ─
html = html.replace(
  /fetch\('quest-answers\.json'\)\s*\n?\s*\.then\(r => r\.json\(\)\)\s*\n?\s*\.then\(data => \{ questAnswers = data; \}\)\s*\n?\s*\.catch\(\(\) => \{ questAnswers = null; \}\);/,
  `// quest-answers.json はインライン埋め込み済み
  questAnswers = QUEST_ANSWERS_INLINE;`
);

// ── 7. 書き出し ──────────────────────────────────────────────────
fs.writeFileSync(htmlPath, html, 'utf8');
console.log(`\nDone! File size: ${Math.round(html.length / 1024)}KB`);
console.log('Images and JSON are now embedded in english-app.html');
